# Congruencia Lineal

In [3]:
import pandas as pd
a=int(input("Ingrese \"a\": "))
b=int(input("Ingrese \"c\": "))
m=int(input("Ingrese \"m\": "))
x0=int(input("Ingrese la semilla: "))
iteraciones=int(input("Ingrese número de iteraciones: "))
Unn=0
Xn=[]
Un=[]
iteracioness=[]
Xnn=x0
i=0
iteracioness.append(i)
i=i+1
Xn.append(Xnn)
Un.append(Unn)
while(i <= iteraciones):
    iteracioness.append(i)
    Xnn= (a * Xnn + b) % m
    Xn.append(Xnn)
    Unn=Xnn/m
    Un.append(Unn)
    i=i+1
data={'iteracion':iteracioness,'Xn':Xn,'Un':Un}
df=pd.DataFrame(data)
df

Ingrese "a": 3
Ingrese "c": 5
Ingrese "m": 19
Ingrese la semilla: 4440
Ingrese número de iteraciones: 35

    iteracion    Xn        Un
0           0  4440  0.000000
1           1     6  0.315789
2           2     4  0.210526
3           3    17  0.894737
4           4    18  0.947368
5           5     2  0.105263
6           6    11  0.578947
7           7     0  0.000000
8           8     5  0.263158
9           9     1  0.052632
10         10     8  0.421053
11         11    10  0.526316
12         12    16  0.842105
13         13    15  0.789474
14         14    12  0.631579
15         15     3  0.157895
16         16    14  0.736842
17         17     9  0.473684
18         18    13  0.684211
19         19     6  0.315789
20         20     4  0.210526
21         21    17  0.894737
22         22    18  0.947368
23         23     2  0.105263
24         24    11  0.578947
25         25     0  0.000000
26         26     5  0.263158
27         27     1  0.052632
28         28     8  0.421053
29         29    10  0.526316
30         30    16  0.842105
31         31    15  0.789474
32         32    12  0.631579
33         33     3  0.157895
34         34    14  0.736842
35         35     9  0.473684